import * as stylex from '@stylexjs/stylex'

import { colors } from '@foldstylex/tokens/colors.stylex.ts'
import { layout } from '@foldstylex/tokens/layout.stylex.ts'

export const sidebarStyles = stylex.create({
  shell: {
    display: 'flex',
    minHeight: '100vh',
    width: '100%',
    colorScheme: 'light dark',
  },
  desktop: {
    display: 'none',
    position: 'fixed',
    top: 0,
    bottom: 0,
    left: 0,
    zIndex: 40,
    width: layout.sidebarWidth,
    flexDirection: 'column',
    fontSize: '1rem',
    backgroundColor: colors.sidebar,
    color: colors.sidebarForeground,
    borderRightWidth: 1,
    borderRightStyle: 'solid',
    borderRightColor: colors.sidebarBorder,
    transitionProperty: 'width',
    transitionDuration: '200ms',
    transitionTimingFunction: 'linear',
  },
  desktopCollapsed: {
    width: layout.sidebarWidthIcon,
  },
  desktopVisible: {
    '@media (min-width: 768px)': {
      display: 'flex',
    },
  },
  header: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.5rem',
    padding: '0.5rem',
    flexShrink: 0,
  },
  content: {
    display: 'flex',
    flex: 1,
    minHeight: 0,
    flexDirection: 'column',
    gap: '0.5rem',
    overflowY: 'auto',
    overflowX: 'hidden',
  },
  contentCollapsed: {
    overflow: 'hidden',
  },
  groupList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.5rem',
    listStyle: 'none',
    margin: 0,
    padding: 0,
  },
  groupListItem: {
    listStyle: 'none',
  },
  footer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.5rem',
    padding: '0.5rem',
    flexShrink: 0,
  },
  group: {
    display: 'flex',
    boxSizing: 'border-box',
    width: '100%',
    minWidth: 0,
    flexDirection: 'column',
    padding: '0.5rem',
  },
  groupLabel: {
    display: 'flex',
    height: '2rem',
    flexShrink: 0,
    alignItems: 'center',
    borderRadius: layout.radiusMd,
    paddingInline: '0.5rem',
    fontSize: '0.75rem',
    fontWeight: 500,
    color: colors.sidebarForegroundMuted,
    outlineStyle: 'none',
    transitionProperty: 'margin, opacity',
    transitionDuration: '200ms',
    transitionTimingFunction: 'linear',
  },
  groupLabelCollapsed: {
    marginTop: '-2rem',
    opacity: 0,
    pointerEvents: 'none',
  },
  collapseHidden: {
    display: 'none',
  },
  groupLabelButton: {
    display: 'flex',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderStyle: 'none',
    backgroundColor: 'transparent',
    padding: 0,
    color: 'inherit',
    font: 'inherit',
    cursor: 'pointer',
    outlineStyle: 'none',
    ':hover': {
      color: colors.sidebarForeground,
      opacity: 1,
    },
  },
  groupChevron: {
    marginLeft: 'auto',
    transitionProperty: 'transform',
    transitionDuration: '200ms',
    transitionTimingFunction: 'ease',
  },
  groupChevronOpen: {
    transform: 'rotate(180deg)',
  },
  menu: {
    display: 'flex',
    width: '100%',
    minWidth: 0,
    flexDirection: 'column',
    gap: '0.25rem',
    listStyle: 'none',
    margin: 0,
    padding: 0,
  },
  menuCollapsed: {
    gap: 0,
  },
  menuItem: {
    position: 'relative',
  },
  menuItemGroup: {
    position: 'relative',
  },
  menuAction: {
    position: 'absolute',
    top: '0.375rem',
    right: '0.25rem',
    display: 'flex',
    aspectRatio: '1',
    width: '1.25rem',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: layout.radiusMd,
    padding: 0,
    color: colors.sidebarForeground,
    backgroundColor: 'transparent',
    borderStyle: 'none',
    cursor: 'pointer',
    outlineStyle: 'none',
    pointerEvents: 'auto',
    transitionProperty: 'opacity, background-color, color',
    transitionDuration: '150ms',
    ':hover': {
      backgroundColor: colors.sidebarAccent,
      color: colors.sidebarAccentForeground,
    },
    ':focus-visible': {
      boxShadow: `0 0 0 2px ${colors.sidebarRing}`,
    },
  },
  menuButton: {
    display: 'flex',
    width: '100%',
    height: '2rem',
    alignItems: 'center',
    gap: '0.5rem',
    overflow: 'hidden',
    borderRadius: layout.radiusMd,
    padding: '0.5rem',
    textAlign: 'left',
    fontSize: '0.875rem',
    lineHeight: 1.25,
    outlineStyle: 'none',
    transitionProperty: 'width, height, padding, background-color, color',
    transitionDuration: '200ms',
    transitionTimingFunction: 'ease-linear',
    textDecoration: 'none',
    color: colors.sidebarForeground,
    backgroundColor: 'transparent',
    borderStyle: 'none',
    cursor: 'pointer',
    ':hover': {
      backgroundColor: colors.sidebarAccent,
      color: colors.sidebarAccentForeground,
    },
    ':focus-visible': {
      boxShadow: `0 0 0 2px ${colors.sidebarRing}`,
    },
  },
  menuButtonLg: {
    height: '3rem',
    padding: '0.5rem',
    fontSize: '0.875rem',
  },
  menuButtonCollapsed: {
    width: '2rem',
    height: '2rem',
    padding: '0.5rem',
  },
  menuButtonLgCollapsed: {
    width: '2rem',
    height: '2rem',
    padding: 0,
  },
  menuButtonInner: {
    display: 'flex',
    width: '100%',
    alignItems: 'center',
    gap: '0.5rem',
  },
  menuButtonInnerCollapsed: {
    width: 'auto',
  },
  menuButtonWithAction: {
    paddingRight: '2rem',
  },
  menuButtonMuted: {
    color: colors.sidebarForegroundMuted,
  },
  menuButtonIconMuted: {
    color: colors.sidebarForegroundMuted,
  },
  menuButtonActive: {
    backgroundColor: colors.sidebarAccent,
    color: colors.sidebarAccentForeground,
    fontWeight: 500,
  },
  menuButtonIcon: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '1rem',
    height: '1rem',
    flexShrink: 0,
  },
  menuButtonLabel: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  menuButtonChevron: {
    width: '1rem',
    height: '1rem',
    marginLeft: 'auto',
    flexShrink: 0,
    transitionProperty: 'transform',
    transitionDuration: '200ms',
    transitionTimingFunction: 'ease',
  },
  menuButtonChevronOpen: {
    transform: 'rotate(90deg)',
  },
  menuSub: {
    display: 'flex',
    minWidth: 0,
    marginInline: '0.875rem',
    marginBlock: '0.125rem',
    transform: 'translateX(1px)',
    flexDirection: 'column',
    gap: '0.25rem',
    borderLeftWidth: 1,
    borderLeftStyle: 'solid',
    borderLeftColor: colors.sidebarBorder,
    paddingInline: '0.625rem',
    paddingBlock: '0.125rem',
    listStyle: 'none',
  },
  menuSubItem: {
    position: 'relative',
  },
  menuSubButton: {
    display: 'flex',
    width: '100%',
    height: '1.75rem',
    minWidth: 0,
    alignItems: 'center',
    gap: '0.5rem',
    overflow: 'hidden',
    borderRadius: layout.radiusMd,
    paddingInline: '0.5rem',
    textAlign: 'left',
    fontSize: '0.875rem',
    lineHeight: 1.25,
    outlineStyle: 'none',
    transform: 'translateX(-1px)',
    textDecoration: 'none',
    color: colors.sidebarForeground,
    backgroundColor: 'transparent',
    borderStyle: 'none',
    cursor: 'pointer',
    ':hover': {
      backgroundColor: colors.sidebarAccent,
      color: colors.sidebarAccentForeground,
    },
    ':focus-visible': {
      boxShadow: `0 0 0 2px ${colors.sidebarRing}`,
    },
  },
  menuSubButtonActive: {
    backgroundColor: colors.sidebarAccent,
    color: colors.sidebarAccentForeground,
    fontWeight: 500,
  },
  inset: {
    display: 'flex',
    flex: 1,
    flexDirection: 'column',
    backgroundColor: colors.background,
    color: colors.foreground,
    transitionProperty: 'margin-left',
    transitionDuration: '200ms',
    transitionTimingFunction: 'linear',
    '@media (min-width: 768px)': {
      marginLeft: layout.sidebarWidth,
    },
  },
  insetCollapsed: {
    '@media (min-width: 768px)': {
      marginLeft: layout.sidebarWidthIcon,
    },
  },
  insetHeader: {
    display: 'flex',
    height: '4rem',
    flexShrink: 0,
    alignItems: 'center',
    gap: '0.5rem',
    paddingInline: '1rem',
  },
  insetHeaderInner: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  insetMain: {
    flex: 1,
    minHeight: 0,
  },
  mobileTrigger: {
    marginLeft: '-0.25rem',
    '@media (min-width: 768px)': {
      display: 'none',
    },
  },
  desktopTrigger: {
    marginLeft: '-0.25rem',
    display: 'none',
    '@media (min-width: 768px)': {
      display: 'block',
    },
  },
  mobileSheet: {
    display: 'flex',
    height: '100%',
    width: layout.sidebarWidthMobile,
    flexDirection: 'column',
    fontSize: '1rem',
    backgroundColor: colors.sidebar,
    color: colors.sidebarForeground,
  },
  mobileSheetPanel: {
    display: 'flex',
    height: '100%',
    flexDirection: 'column',
  },
  mobileSheetHeader: {
    display: 'flex',
    height: '3rem',
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: '0.5rem',
    paddingInline: '1rem',
  },
  mobileOnly: {
    '@media (min-width: 768px)': {
      display: 'none',
    },
  },
  mobileOverlay: {
    position: 'fixed',
    inset: 0,
    zIndex: 50,
    backgroundColor: 'rgb(0 0 0 / 0.5)',
  },
  brandLogo: {
    display: 'flex',
    aspectRatio: '1',
    alignItems: 'center',
    justifyContent: 'center',
    width: '2rem',
    height: '2rem',
    flexShrink: 0,
    borderRadius: layout.radiusLg,
    backgroundColor: colors.sidebarPrimary,
    color: colors.sidebarPrimaryForeground,
  },
  brandText: {
    display: 'grid',
    flex: 1,
    minWidth: 0,
    textAlign: 'left',
    lineHeight: 1.25,
  },
  brandName: {
    fontSize: '0.875rem',
    fontWeight: 500,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  brandSubtitle: {
    fontSize: '0.75rem',
    color: colors.sidebarForeground,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  userAvatar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '2rem',
    height: '2rem',
    flexShrink: 0,
    borderRadius: layout.radiusLg,
    backgroundColor: colors.sidebarAccent,
    color: colors.sidebarAccentForeground,
    fontSize: '0.75rem',
    fontWeight: 600,
  },
  srOnly: {
    position: 'absolute',
    width: '1px',
    height: '1px',
    padding: 0,
    margin: '-1px',
    overflow: 'hidden',
    clip: 'rect(0, 0, 0, 0)',
    whiteSpace: 'nowrap',
    borderWidth: 0,
  },
})